<?php

declare(strict_types=1);

namespace WcoApi\Command;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use WcoApi\Entity\RecordingDownload;

#[AsCommand(
    name: 'wco:db-install',
    description: 'Tworzy tabelę(e) WCO w DB hosta lub generuje migrację Doctrine'
)]
final class DbInstallCommand extends Command
{
    public function __construct(
        private readonly ?EntityManagerInterface $em = null,
        private readonly string $projectDir = '',
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('dump-sql', null, InputOption::VALUE_NONE, 'Tylko wypisz SQL (bez wykonania)')
            ->addOption('force', 'f', InputOption::VALUE_NONE, 'Wykonaj CREATE/ALTER (SchemaTool)')
            ->addOption('migration', 'm', InputOption::VALUE_NONE, 'Zapisz plik migracji w migrations/ hosta');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        if ($this->em === null) {
            $io->error('Brak Doctrine ORM — zainstaluj doctrine/orm + doctrine/doctrine-bundle w projekcie hosta.');

            return Command::FAILURE;
        }

        $meta = [$this->em->getClassMetadata(RecordingDownload::class)];
        $tool = new SchemaTool($this->em);
        $sql = $tool->getUpdateSchemaSql($meta);

        if ($sql === []) {
            $io->success('Schemat WCO jest już aktualny (brak zmian).');

            return Command::SUCCESS;
        }

        if ($input->getOption('dump-sql') || (!$input->getOption('force') && !$input->getOption('migration'))) {
            $io->section('SQL do wykonania (tabele WCO)');
            foreach ($sql as $line) {
                $io->writeln($line . ';');
            }
            $io->note('Uruchom z --force żeby zastosować, lub --migration żeby zapisać migrację.');

            return Command::SUCCESS;
        }

        if ($input->getOption('migration')) {
            $path = $this->writeMigration($sql);
            $io->success(sprintf('Zapisano migrację: %s', $path));
            $io->writeln('Dalej: <info>php bin/console doctrine:migrations:migrate</info>');

            return Command::SUCCESS;
        }

        $tool->updateSchema($meta);
        $io->success('Zaktualizowano schemat WCO w bazie (SchemaTool).');

        return Command::SUCCESS;
    }

    /** @param list<string> $sql */
    private function writeMigration(array $sql): string
    {
        $dir = $this->projectDir . DIRECTORY_SEPARATOR . 'migrations';
        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new \RuntimeException('Nie można utworzyć katalogu migrations/: ' . $dir);
        }

        $ts = (new \DateTimeImmutable('now', new \DateTimeZone('UTC')))->format('YmdHis');
        $class = 'Version' . $ts . '_WcoApi';
        $file = $dir . DIRECTORY_SEPARATOR . $class . '.php';

        $upLines = [];
        foreach ($sql as $line) {
            $upLines[] = '        $this->addSql(' . var_export($line, true) . ');';
        }
        $upBody = implode("\n", $upLines);

        $content = <<<PHP
<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\\DBAL\\Schema\\Schema;
use Doctrine\\Migrations\\AbstractMigration;

/**
 * Auto-generated by wco:db-install --migration (WcoApiBundle).
 */
final class {$class} extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'WCO API: tabela wco_recording_download (tracking pobrań)';
    }

    public function up(Schema \$schema): void
    {
{$upBody}
    }

    public function down(Schema \$schema): void
    {
        \$this->addSql('DROP TABLE IF EXISTS wco_recording_download');
    }
}

PHP;

        if (file_put_contents($file, $content) === false) {
            throw new \RuntimeException('Nie zapisano migracji: ' . $file);
        }

        return $file;
    }
}
